name: Deploy to GitHub pages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init new repo in dist folder and commit generated files
      run: |
       git checkout -b deploy
       git pull origin main
       git add .
       git commit -m "deploy"
       git push origin deploy
        