name: Deploy to GitHub pages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Switch branch and deploy
      run: |
        git checkout -b deploy
        git push origin deploy

    - name: Pull from main
      run: |
        git checkout deploy
        git pull origin deploy

    - name: Commit changes
      run: |
        git add .
        git commit -m "Deploy changes from main"
        git push origin deploy
